### ISSUE TITLE
Nuxt Js Support

### ISSUE THREAD

**Issue by vishnurnair93** [john015/vue-load-image#2]
When using the plugin in nuxtjs it shows window is not defined.

Any workaround suggestions?

**Comment by john015** [comment]
I can't give you a clear answer because I`ve never used nuxt.js before, but here in [this project](https://github.com/quannt/vue-news/blob/a85b38f114bda70e17a92e925545c987dd5d1e5e/components/common/CommonImage.vue), it used the vue-load-image source code directly in the project.

See [this project source code](https://github.com/quannt/vue-news/blob/a85b38f114bda70e17a92e925545c987dd5d1e5e/components/common/CommonImage.vue).

**Comment by vishnurnair93** [comment]
Thanks for the feedback appreciate it 👍
